travis:
  secure:
    BINSTAR_TOKEN: M7GBltcCINgyfw2sWwyiq09TMWLaQek05R7U3s20HWv1gUCOuZzo46fARP6aoCBAXH1uVZ02Z4Avv3seX9y1IKt/S9AC/uMxFa2SjIzwO4y1LM93H+Qw8sqm61tMfMnokYYgk9vbxjuCEhIl1N/V8OwvDlW13fuh6ISt3HJCLpefsKwzV8KiR+V6peflmz1QgW9VqnIeVXHOhmR0NjIrXUBb+3CGpqcMTMESk2/34G/+oG2VWfQd6t2tjhKXlzBX2RTlhRPUpwrqU5yNAdpRrYnV+ipkFYL9yxKI4zycbBr/08Es4iPHkflFbjmf4xvosPmF6uDeOfXK24Yp0qBkmjy0l7q7H1ccjUoFQXyQsG5AMFejY6VYbFeLx8eNuJtjeoWNY62G1xeMDwGw5d4UcelTBuXKRbXi89cFVp3J55u4XwBVxL0Y/m0oQbFxjmjLAsJxTcwzqdIbq3Kkj0mswFhe6dz0jDjeoiHJtNhBjOwhrDeLSEEE9QnKDtueUN9E1/2muZQ4kUq4mR0X1u5fJcdRmrvWqqIjuOGSrpblHY5BN7SfeRIt6EzJm1XjpurZKMJ8Bwt/3CMuMWvlaXnzdlPvQvTuggr8e8+GevgxmpKGCfBsf62xeYJs9+2+ZZqDRv9F8cOfsRaJE2j2ZEZ/27HMOgAYJLdbPRtUKfdASK8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
