appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GN1FpjMiN9wqQXXc7i+MO4RCjyQJCRWKpywqqXfho+NMlwzFciRmGXaDSVKyQWdVQdun6izYVjrRthsRn6s1Ys6ExMY7WENHV61XeSghHqBj3auCopl2Lu0GfzZAmPrfyhLHsp3jx4M7b0zTJl6pNdwaR0Lskt0bIsb4y7BhZpxzOICChocoasUe7MVobl7ISGUAcH5d1/S1KiVxNrQILZnCAC60u/7rixwmY+46eZe+hKIow+WJkvLMpgeh25EGQkrSgi/PXEIL5FxHaw0itZ0g3lVLCE92uaMdycgiQ4Y312Np2VxCQfgqNOQZTi6HWuCWybsII9G5nthzeKcro11URLozV0kvfNHV+RdNlH/jFAKulGCWvOg6DYMD/Veb72unUWM5Gfy8FgnqCPhcrafe1/C1RqUF6yqF6RwoJHdHdode6IMO2XVtxYHxETIyWblzXwol+K4eFmy5Op6sQlD6GXj2tA90tsYtj4k0+JGHAm6J/yBQ1pb/jBHrKW+/q59VQQrlOtJE0K1kHbR/OqOy0xgigkkDIbpdphWlv+LQprge4fFuSMnEyRt1N606GpGAo3mIVlL2i7xBBalMJCjLGIVRvhg1bOKe9DcKotkwxtf67DOewf+vpS7tUtAIv5FkdNShEKzlPx86gDgjxRfV/0q7DN5tYn3vFtcokek=}
